-- ╭─────────────────────────────────────────────────────────╮
-- │ ICONS                                                   │
-- ╰─────────────────────────────────────────────────────────╯

---@class core.icons
local M = {}

-- M.vscode = {
--   ActiveTS = " ",
--   BufferClose = "",
--   DefaultFile = "",
--   Diagnostic = "",
--   FoldClosed = "",
--   FoldOpened = "",
--   Git = "",
--   GitConflict = "",
--   MacroRecording = "",
--   Paste = "",
--   Selected = "",
--   TabClose = "",
-- }

M.kind = {
  Array = "",
  Boolean = "",
  Class = "",
  Color = "",
  Constant = "",
  Constructor = "",
  Enum = "",
  EnumMember = "",
  Event = "",
  Field = "",
  File = "",
  Folder = "",
  Function = "",
  Interface = "",
  Key = "",
  Keyword = "",
  Method = "",
  Module = "",
  Namespace = "",
  Null = "󰟢",
  Number = "",
  Object = "",
  Operator = "",
  Package = "",
  Property = "",
  Reference = "",
  Snippet = "",
  String = "",
  Struct = "",
  Text = "",
  TypeParameter = "",
  Unit = "",
  Value = "",
  Variable = "",
}

M.git = {
  LineAdded = "",
  LineModified = "",
  LineRemoved = "",
  FileUnstaged = "󰄱",
  FileStaged = "󰱒",
  FileIgnored = "",
  FileRenamed = "",
  FileUnmerged = "",
  FileUntracked = "",
  -- Diff = "",
  -- Repo = "",
  Octoface = "",
  Branch = "",
}

M.ui = {
  ActiveLSP = "",
  -- ArrowCircleDown = "",
  -- ArrowCircleLeft = "",
  -- ArrowCircleRight = "",
  -- ArrowCircleUp = "",
  -- BoldArrowDown = "",
  -- BoldArrowLeft = "",
  -- BoldArrowRight = "",
  -- BoldArrowUp = "",
  -- BoldClose = "",
  -- BoldDividerLeft = "",
  -- BoldDividerRight = "",
  BoldLineLeft = "▎",
  BookMark = "",
  -- BoxChecked = "",
  -- Bug = "",
  -- Calendar = "",
  -- Check = "",
  ChevronShortRight = "",
  Circle = "",
  -- Close = "",
  -- CloudDownload = "",
  -- Code = "",
  -- Comment = "",
  -- Dashboard = "",
  -- DebugConsole = "",
  -- DividerLeft = "",
  -- DividerRight = "",
  DoubleChevronRight = "»",
  Ellipsis = "",
  File = "",
  -- FileSymlink = "",
  -- Files = "",
  -- FindFile = "󰈞",
  -- FindText = "󰊄",
  -- Fire = "",
  -- FolderEmpty = "",
  -- FolderSymlink = "",
  -- Forward = "",
  -- History = "",
  -- Lightbulb = "",
  LineLeft = "▏",
  -- LineMiddle = "│",
  -- List = "",
  Lock = "",
  -- NewFile = "",
  -- Note = "",
  Package = "",
  PackagePending = "",
  PackageInstalled = "󰄳",
  PackageUninstalled = "",
  -- Pencil = "󰏫",
  -- Plus = "",
  -- Project = "",
  -- Stacks = "",
  -- Scopes = "",
  Search = "",
  -- SignIn = "",
  SignOut = "",
  Tab = "󰌒",
  -- Table = "",
  -- Target = "󰀘",
  Text = "",
  -- Tree = "",
  Triangle = "󰐊",
  -- TriangleShortArrowDown = "",
  -- TriangleShortArrowLeft = "",
  -- TriangleShortArrowRight = "",
  -- TriangleShortArrowUp = "",
  -- Watches = "󰂥",
}

M.diagnostics = {
  Error = "",
  Warn = "",
  Info = "",
  Hint = "",
}

M.dap = {
  Breakpoint = "",
  BreakpointCondition = "",
  BreakpointRejected = "",
  LogPoint = "",
  Stopped = "",
}

-- M.misc = {
--   Robot = "󰚩",
--   Squirrel = "",
--   Tag = "",
--   Watch = "",
--   Smiley = "",
--   Package = "",
--   CircuitBoard = "",
-- }

return M
