# ╭──────────────────────────────────────────────────────────╮
# │ SETTINGS                                                 │
# ╰──────────────────────────────────────────────────────────╯

---
font:
  size: 14
  sans:
    family: "Rubik"
    weight: "Bold"
  nerd:
    family: "MonaspiceNe Nerd Font"
    weight: "Regular"
