# ╭──────────────────────────────────────────────────────────╮
# │ Windows                                                  │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  # ── Essentials (get installed before the other packages) ──────────────
  essentials:
    winget:
      - "twpayne.chezmoi"
      - "Git.Git"
      - "Nushell.Nushell"
apps:
  work:
    winget:
      - "Docker.DockerDesktop"
  personal:
    winget:
      - "XPDM5VSMTKQLBJ" # Battle.net
      - "Blitz.Blitz"
      - "Overwolf.CurseForge"
      - "EpicGames.EpicGamesLauncher"
      - "FACEITLTD.FACEITAC"
      - "Mojang.MinecraftLauncher"
      - "Valve.Steam"
      - "Stremio.Stremio"
      - "RiotGames.Valorant.EU"
  winget:
    - "Bitwarden.Bitwarden"
    - "ente-io.auth-desktop"
    - "Logitech.OptionsPlus"
    - "Nextcloud.NextcloudDesktop"
    - "Microsoft.PowerToys"
    - "Proton.ProtonDrive"
    - "Proton.ProtonMail"
    - "Proton.ProtonVPN"
    - "Nilesoft.Shell"
    - "OpenWhisperSystems.Signal"
    - "Spotify.Spotify"
    - "Vencord.Vesktop"
    - "Microsoft.VisualStudioCode"
    - "9NKSQGP7F2NH" # WhatsApp Desktop
    - "Zen-Team.Zen-Browser"
  manual:
    - "0xProto Nerd Font"
    - "Iosevka Nerd Font"
