---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2

blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: os
        style: plain
        foreground_templates:
          - "{{ if eq .OS 'windows' }}#00ACEE{{ end }}"
          - "{{ if eq .OS 'arch' }}#1894D4{{ end }}"
          - "{{ if eq .OS 'ubuntu' }}#F47421{{ end }}"
        template: "{{ .Icon }}  "
      - type: path
        style: plain
        background: transparent
        foreground: blue
        template: "{{ .Path }}"
        properties:
          folder_separator_icon: "/"
          style: full
      - type: git
        style: plain
        foreground: p:grey
        background: transparent
        template:
          " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end
          }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end
          }}</>"
        properties:
          branch_icon: ""
          commit_icon: "@"
          fetch_status: true
  - type: rprompt
    overflow: hidden
    segments:
      - type: executiontime
        style: plain
        foreground: yellow
        background: transparent
        template: "{{ .FormattedMs }}"
        properties:
          threshold: 5000
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        foreground_templates:
          - "{{if gt .Code 0}}red{{end}}"
          - "{{if eq .Code 0}}magenta{{end}}"
        background: transparent
        template: ❯
transient_prompt:
  foreground_templates:
    - "{{if gt .Code 0}}red{{end}}"
    - "{{if eq .Code 0}}magenta{{end}}"
  background: transparent
  template: "❯ "
secondary_prompt:
  foreground: magenta
  background: transparent
  template: "❯❯ "
