# ╭──────────────────────────────────────────────────────────╮
# │ OH MY POSH CONFIG                                        │
# ╰──────────────────────────────────────────────────────────╯

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2
console_title_template: "{{ if .WSL }}WSL: {{ end }}{{ .Shell }} in {{ .Folder }}"

blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: os
        style: plain
        foreground_templates:
          - '{{ if eq .OS "nixos" }}#5277C3{{ end }}'
          - '{{ if eq .OS "windows" }}#00ACEE{{ end }}'
          - '{{ if eq .OS "raspbian" }}#C51D4A{{ end }}'
        background: transparent
        template: "{{ .Icon }} "
      - type: path
        style: plain
        background: transparent
        foreground: blue
        template: "{{ .Path }}"
        properties:
          folder_separator_icon: "/"
          style: full
      - type: git
        style: plain
        foreground: "#F3C267"
        foreground_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}"
          - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}"
          - "{{ if gt .Ahead 0 }}#B388FF{{ end }}"
          - "{{ if gt .Behind 0 }}#B388FF{{ end }}"
        background: transparent
        properties:
          fetch_status: true
          fetch_upstream_icon: true
  - type: rprompt
    overflow: hidden
    segments:
      - type: executiontime
        style: plain
        foreground: green
        foreground_templates:
          - "{{ if gt .Code 0 }}red{{ end }}"
        background: transparent
        properties:
          threshold: 5000
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        foreground_templates:
          - "{{ if or .Root (gt .Code 0) }}red{{ end }}"
          - "{{ if eq .Code 0 }}magenta{{ end }}"
        background: transparent
        template: "{{ if .Root }}{{ else }}{{ end }}"
transient_prompt:
  foreground_templates:
    - "{{ if gt .Code 0 }}red{{ end }}"
    - "{{ if eq .Code 0 }}magenta{{ end }}"
  background: transparent
  template: "❯ "
secondary_prompt:
  foreground: magenta
  background: transparent
  template: "❯❯ "
