# ╭──────────────────────────────────────────────────────────╮
# │ APPS                                                     │
# ╰──────────────────────────────────────────────────────────╯

---
apps:
  common:
    - name: "Bitwarden"
      mac: "bitwarden"
      win: "Bitwarden.Bitwarden"
    - name: "Docker"
      mac: "docker"
      win: "Docker.DockerDesktop"
    - name: "Discord"
      mac: "discord"
      win: "Discord.Discord"
    - name: "Figma"
      mac: "figma"
      win: "Figma.Figma"
    - name: "Firefox"
      mac: "firefox"
      win: "Mozilla.Firefox"
    - name: "Google Chrome"
      mac: "google-chrome"
      win: "Google.Chrome"
    - name: "IntelliJ IDEA Ultimate Edition"
      mac: "intellij-idea"
      win: "JetBrains.IntelliJIDEA.Ultimate"
    - name: "Logi Options+"
      mac: "logi-options-plus"
      win: "Logitech.OptionsPlus"
    - name: "Notion"
      mac: "notion"
      win: "Notion.Notion"
    - name: "Notion Calendar"
      mac: "notion-calendar"
      win: "Notion.NotionCalendar"
    - name: "PDFgear"
      mac:
        mas:
          name: "PDFgear"
          id: "6469021132"
      win: "PDFgear.PDFgear"
    - name: "Spark"
      mac: "readdle-spark"
      win: "Readdle.Spark"
    - name: "Spotify"
      mac: "spotify"
      win: "Spotify.Spotify"
    - name: "Visual Studio Code"
      mac: "visual-studio-code"
      win: "Microsoft.VisualStudioCode"
    - name: "WebStorm"
      mac: "webstorm"
      win: "JetBrains.WebStorm"
    - name: "WezTerm"
      mac: "wezterm"
      win: "wez.wezterm"
    - name: "WhatsApp Desktop"
      mac: "whatsapp"
      win: "9NKSQGP7F2NH"
    - name: "Zed"
      mac: "zed"
