# ╭──────────────────────────────────────────────────────────╮
# │ Arch Linux                                               │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  arch:
    pacman:
      - "bluez" # Bluetooth
      - "bluez-utils" # Bluetooth
      - "brightnessctl" # Brightness control for internal monitors
      - "desktop-file-utils" # Utilities for working with desktop entries
      - "ddcutil" # Required for `ddcci-driver-linux`
      - "docker" # Containerization
      - "docker-compose" # Required for `docker`
      - "dnsmasq" # Required for `libvirt`
      - "easyeffects" # Audio effects for PipeWire applications
      - "efibootmgr" # Required for `grub`
      - "grub" # Boot loader
      - "gst-plugin-pipewire" # Required for `pipewire`
      - "htop" # Process monitor
      - "hypridle" # Idle daemon for Hyprland
      - "hyprland" # Wayland compositor
      - "hyprlock" # Lock screen for Hyprland
      - "hyprpaper" # Wallpaper utility for Hyprland
      - "i2c-tools" # Required for `ddcutil`
      - "iptables-nft" # Required for `libvirt`
      - "iwd" # Wireless daemon
      - "java-environment-common" # containing common files for JDK
      - "jdk-openjdk" # Latest JDK
      - "kvantum" # Qt6 theme engine
      - "kvantum-qt5" # Qt6 theme engine
      - "libpulse" # Required for `pipewire-pulse`
      - "libvirt" # collection of software that provides a convenient way to manage VM's
      - "man-db" # man for Arch
      - "networkmanager" # Network manager
      - "noto-fonts-emoji" # Font: Noto Emoji Color
      - "openbsd-netcat" # Required for `libvirt`
      - "openssh" # SSH protocol implementation
      - "otf-monaspace-nerd" # Font: MonaspiceNe Nerd Font
      - "pacman-contrib" # Required for `paccache`
      - "pavucontrol" # Volume control tool ("mixer") for PulseAudio
      - "pipewire" # Multimedia framework
      - "pipewire-audio" # Audio
      - "pipewire-alsa" # ALSA support
      - "pipewire-jack" # JACK support
      - "pipewire-pulse" # PulseAudio support
      - "playerctl" # Media control
      - "polkit-gnome" # Authentication agent
      - "power-profiles-daemon" # Power profiles
      - "qt5-wayland" # Widget toolkit
      - "qt6-wayland" # Widget toolkit
      - "sddm" # Display manager
      - "slurp" # Region selection for Wayland compositors
      - "smartmontools" # analyzing and monitoring storage devices
      - "swappy" # Wayland native snapshot editing tool
      - "ttf-nerd-fonts-symbols" # Font: Symbols Nerd Font
      - "waybar" # Wayland bar
      - "wf-recorder" # Recording program for wlroots-based compositors
      - "wireless_tools" # Manipulate the Wireless Extensions
      - "wireplumber" # Volume control with PipeWire
      - "wpa_supplicant" # Supplicant
      - "xdg-desktop-portal" # Desktop integration portal for sandboxed apps
      - "xdg-desktop-portal-hyprland" # Required for `Hyprland`
      - "xdg-desktop-portal-wlr" # Required for `Hyprland`
      - "xdg-user-dirs" # Manage "well known" user directories
      - "xdg-utils" # Utilities for managing XDG MIME Applications
    paru:
      - "adw-gtk3-git" # System theme (customizable with `gradience`)
      - "ddcci-driver-linux-dkms-git" # Expose external monitors in `sysfs`
      - "easyeffects-presets" # Control EasyEffects from the polybar status bar
      - "gradience" # Customizing Libadwaita applications and the adw-gtk3 theme
      - "hyprpicker-git" # Color picker feature in Hyprland
      - "hyprshade-git" # Switching screen shaders in Hyprland
      - "mpris-proxy-service" # mpris-proxy automation
      - "safeeyes" # Reduce and prevent repetitive strain injury
      - "ttf-rubik-vf" # Font: Rubik
      - "wayshot" # Screenshot tool for wlroots compositors
      - "wl-clip-persist" # Persistent clipboard
apps:
  arch:
    pacman:
      - "dconf-editor" # dconf editor
      - "geary" # Email client
      - "gnome-calculator" # Calculator
      - "gnome-clocks" # Timers
      - "gnome-control-center" # System settings
      - "gnome-disk-utility" # Disk utility
      - "gnome-screenshot" # Screenshot
      - "gnome-system-monitor" # Task manager
      - "gnome-terminal" # Required dependency for `docker`
      - "loupe" # Image viewer
      - "nautilus" # File Manager
      - "qemu-full" # VM support
      - "qt5ct" # Qt5 Configuration Tool
      - "qt6ct" # Qt6 Configuration Tool
      - "virt-manager" # Desktop user interface for managing VM's
      - "vlc" # Media player
