# ╭──────────────────────────────────────────────────────────╮
# │ macOS                                                    │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  mac:
    formulae:
      - "bc" # for TokyoNight TMUX
      - "nowplaying-cli"
      - "jstkdng/programs/ueberzugpp"

apps:
  mac:
    casks:
      - "alt-tab"
      - "aldente"
      - "ankerwork"
      - "appcleaner"
      - "betterdisplay"
      - "command-x"
      - "font-rubik"
      - "font-monaspace-nerd-font"
      - "font-noto-color-emoji"
      - "font-symbols-only-nerd-font"
      - "iina"
      - "latest"
      - "maccy"
      - "mission-control-plus"
      - "raycast"
      - "rectangle"
    mas:
      - name: "Dropover"
        id: "1355679052"
    manual:
      - "TinkerTool"
