# ╭──────────────────────────────────────────────────────────╮
# │ PACKAGES                                                 │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  npm:
    - "npkill"
    - "tree-sitter-cli"
    - "turbo"
