# ╭──────────────────────────────────────────────────────────╮
# │ PACKAGES                                                 │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  # ── Essentials (get installed before the other packages) ──────────────
  essentials:
    - name: "base-devel"
      arch: "base-devel"
    - name: "chezmoi"
      arch: "chezmoi"
      mac: "chezmoi"
      win: "twpayne.chezmoi"
    - name: "curl"
      arch: "curl"
    - name: "git"
      arch: "git"
      mac: "git"
      win: "Git.Git"
    - name: "gum"
      arch: "gum"
      mac: "gum"
      win: "charmbracelet.gum"
    - name: "pwsh"
      win: "Microsoft.PowerShell"
    - name: "python"
      arch: "python"
      win: "Python.Python.3.12"
    - name: "pip"
      arch: "python-pip"
    - name: "unzip"
      arch: "unzip"
    - name: "volta"
      arch:
        paru: "volta-bin"
      mac: "volta"
      win: "Volta.Volta"
    - name: "wget"
      arch: "wget"
      mac: "wget"
    - name: "rustup"
      arch:
        custom: |
          sudo pacman -S --needed --noconfirm rustup
          rustup update
          rustup default stable
      mac:
        custom: |
          brew install rustup-init
          rustup update
          rustup default stable
      win:
        custom: |
          winget install -e --accept-package-agreements --accept-source-agreements --id Rustlang.Rustup
          rustup update
          rustup default stable
  volta:
    - "node"
    - "pnpm"
    - "yarn"
  # ── Packages ──────────────────────────────────────────────────────────
  common:
    - name: "bat"
      arch: "bat"
      mac: "bat"
      win: "sharkdp.bat"
    - name: "delta"
      arch: "git-delta"
      mac: "git-delta"
      win: "dandavison.delta"
    - name: "eza"
      arch: "eza"
      mac: "eza"
      win: "eza-community.eza"
    - name: "fd"
      arch: "fd"
      mac: "fd"
      win: "sharkdp.fd"
    - name: "fastfetch"
      arch: "fastfetch"
      mac: "fastfetch"
      win: "Fastfetch-cli.Fastfetch"
    - name: "fzf"
      arch: "fzf"
      mac: "fzf"
      win: "junegunn.fzf"
    - name: "java"
      mac: "openjdk"
      win: "ojdkbuild.ojdkbuild"
    - name: "lazydocker"
      arch:
        paru: "lazydocker"
      mac: "jesseduffield/lazydocker/lazydocker"
      win: "JesseDuffield.lazydocker"
    - name: "lazygit"
      arch: "lazygit"
      mac: "jesseduffield/lazygit/lazygit"
      win: "JesseDuffield.lazygit"
    - name: "less"
      arch: "less"
      mac: "less"
      win: "jftuga.less"
    - name: "nvim"
      arch: "neovim"
      mac: "neovim"
      win: "Neovim.Neovim"
    - name: "oh-my-posh"
      arch:
        paru: "oh-my-posh-bin"
      mac: "jandedobbeleer/oh-my-posh/oh-my-posh"
      win: "JanDeDobbeleer.OhMyPosh"
    - name: "rg"
      arch: "ripgrep"
      mac: "ripgrep"
      win: "BurntSushi.ripgrep.MSVC"
    - name: "zoxide"
      arch: "zoxide"
      mac: "zoxide"
      win: "ajeetdsouza.zoxide"
  npm:
    - "npkill"
    - "tree-sitter-cli"
    - "turbo"
  cargo:
    - "nvim-switcher"
