# ╭──────────────────────────────────────────────────────────╮
# │ SETTINGS                                                 │
# ╰──────────────────────────────────────────────────────────╯

---
font:
  size: 14
  sans:
    family: "Geist"
    weight: "Bold"
  nerd:
    family: "GeistMono NF"
    weight: "Regular"
