# ╭──────────────────────────────────────────────────────────╮
# │ Windows                                                  │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  win:
    winget:
      - "9MZNMNKSM73X" # Arch WSL
      - "Microsoft.DotNet.SDK.8"
      - "LLVM.LLVM"
      - "ojdkbuild.ojdkbuild"
      - "mbuilov.sed"
      - "gerardog.gsudo"
      - "Microsoft.VCRedist.2015+.x64"
    modules:
      - "PSFzf"
apps:
  win:
    winget:
      - "Guru3D.Afterburner"
      - "Bitwarden.Bitwarden"
      - "Google.Chrome"
      - "Docker.DockerDesktop"
      - "Discord.Discord"
      - "Figma.Figma"
      - "Mozilla.Firefox"
      - "JetBrains.IntelliJIDEA.Ultimate"
      - "MicaForEveryone.MicaForEveryone"
      - "Notion.Notion"
      - "Notion.NotionCalendar"
      - "Logitech.OptionsPlus"
      - "PDFgear.PDFgear"
      - "Microsoft.PowerToys"
      - "Nilesoft.Shell"
      - "Readdle.Spark"
      - "Spotify.Spotify"
      - "Microsoft.VisualStudio.2022.Community"
      - "Microsoft.VisualStudioCode"
      - "JetBrains.WebStorm"
      - "wez.wezterm"
      - "9P8LTPGCBZXD" # Wintoys (installed from Microsoft Store)
      - "9NKSQGP7F2NH" # WhatsApp Desktop
    manual:
      - "AnkerWork"
      - "Rubik Font"
      - "MonaspiceNe Nerd Font"
      - "Symbols Nerd Font"
      - "Noto Color Emoji Font"
