# ╭──────────────────────────────────────────────────────────╮
# │ Windows                                                  │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  win:
    winget:
      - "9MZNMNKSM73X" # Arch WSL
      - "Microsoft.DotNet.SDK.8"
      - "LLVM.LLVM"
      - "mbuilov.sed"
      - "gerardog.gsudo"
      - "Microsoft.VCRedist.2015+.x64"
    modules:
      - "PSFzf"
apps:
  win:
    winget:
      - "Guru3D.Afterburner"
      - "MicaForEveryone.MicaForEveryone"
      - "Microsoft.PowerToys"
      - "Nilesoft.Shell"
      - "Microsoft.VisualStudio.2022.Community"
      - "9P8LTPGCBZXD" # Wintoys (installed from Microsoft Store)
    manual:
      - "AnkerWork"
      - "Rubik Font"
      - "MonaspiceNe Nerd Font"
      - "Symbols Nerd Font"
      - "Noto Color Emoji Font"
