# ╭──────────────────────────────────────────────────────────╮
# │ Windows                                                  │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  win:
    winget:
      - "sharkdp.bat"
      - "dandavison.delta"
      - "Microsoft.DotNet.SDK.8"
      - "eza-community.eza"
      - "sharkdp.fd"
      - "Fastfetch-cli.Fastfetch"
      - "junegunn.fzf"
      - "gerardog.gsudo"
      - "JesseDuffield.Lazydocker"
      - "JesseDuffield.lazygit"
      - "jftuga.less"
      - "LLVM.LLVM"
      - "Neovim.Neovim"
      - "JanDeDobbeleer.OhMyPosh"
      - "ojdkbuild.ojdkbuild"
      - "BurntSushi.ripgrep.MSVC"
      - "mbuilov.sed"
      - "Microsoft.VCRedist.2015+.x64"
      - "ajeetdsouza.zoxide"
    modules:
      - "PSFzf"
apps:
  win:
    winget:
      - "Bitwarden.Bitwarden"
      - "Google.Chrome"
      - "Docker.DockerDesktop"
      - "Discord.Discord"
      - "Figma.Figma"
      - "Mozilla.Firefox"
      - "MicaForEveryone.MicaForEveryone"
      - "Notion.Notion"
      - "Logitech.OptionsPlus"
      - "Nextcloud.NextcloudDesktop"
      - "Microsoft.PowerToys"
      - "Nilesoft.Shell"
      - "OpenWhisperSystems.Signal"
      - "Spotify.Spotify"
      - "Microsoft.VisualStudio.2022.Community"
      - "Microsoft.VisualStudioCode"
      - "wez.wezterm"
      - "9P8LTPGCBZXD" # Wintoys (installed from Microsoft Store)
      - "9NKSQGP7F2NH" # WhatsApp Desktop
    manual:
      - "AnkerWork"
      - "Rubik Font"
      - "MonaspiceNe Nerd Font"
      - "Symbols Nerd Font"
      - "Noto Color Emoji Font"
