# ╭──────────────────────────────────────────────────────────╮
# │ Windows                                                  │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  # ── Essentials (get installed before the other packages) ──────────────
  essentials:
    winget:
      - "twpayne.chezmoi"
      - "Git.Git"
      - "charmbracelet.gum"
      - "Microsoft.PowerShell"
  winget:
    - "sharkdp.bat"
    - "dandavison.delta"
    - "eza-community.eza"
    - "Fastfetch-cli.Fastfetch"
    - "junegunn.fzf"
    - "JesseDuffield.lazygit"
    - "JanDeDobbeleer.OhMyPosh"
    - "ajeetdsouza.zoxide"
  pwsh_gallery:
    - "PSFzf"
apps:
  work:
    winget:
      - "Docker.DockerDesktop"
      - "wez.wezterm"
  personal:
    winget:
      - "XPDM5VSMTKQLBJ" # Battle.net
      - "Blitz.Blitz"
      - "Overwolf.CurseForge"
      - "EpicGames.EpicGamesLauncher"
      - "FACEITLTD.FACEITAC"
      - "Mojang.MinecraftLauncher"
      - "Valve.Steam"
      - "RiotGames.Valorant.EU"
  winget:
    - "Bitwarden.Bitwarden"
    - "Logitech.OptionsPlus"
    - "Nextcloud.NextcloudDesktop"
    - "Microsoft.PowerToys"
    - "Proton.ProtonDrive"
    - "Proton.ProtonMail"
    - "Proton.ProtonVPN"
    - "Nilesoft.Shell"
    - "OpenWhisperSystems.Signal"
    - "Spotify.Spotify"
    - "Stremio.Stremio"
    - "Vencord.Vesktop"
    - "Microsoft.VisualStudioCode"
    - "9NKSQGP7F2NH" # WhatsApp Desktop
    - "Zen-Team.Zen-Browser"
  manual:
    - "CommitMono Nerd Font"
    - "Iosevka Nerd Font"
    - "VictorMono Nerd Font"
    - "AnkerWork" 
    - "Zen Browser"