# ╭──────────────────────────────────────────────────────────╮
# │ Windows                                                  │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  # ── Essentials (get installed before the other packages) ──────────────
  essentials:
    winget:
      - "twpayne.chezmoi"
      - "Git.Git"
      - "charmbracelet.gum"
      - "Microsoft.PowerShell"
  winget:
    - "sharkdp.bat"
    - "dandavison.delta"
    - "eza-community.eza"
    - "Fastfetch-cli.Fastfetch"
    - "junegunn.fzf"
    - "JesseDuffield.lazygit"
    - "JanDeDobbeleer.OhMyPosh"
    - "ajeetdsouza.zoxide"
  pwsh_gallery:
    - "PSFzf"
apps:
  winget:
    - "Bitwarden.Bitwarden"
    - "Docker.DockerDesktop"
    - "Logitech.OptionsPlus"
    - "Nextcloud.NextcloudDesktop"
    - "Microsoft.PowerToys"
    - "Proton.ProtonDrive"
    - "Proton.ProtonMail"
    - "Proton.ProtonVPN"
    - "Nilesoft.Shell"
    - "OpenWhisperSystems.Signal"
    - "Spotify.Spotify"
    - "Stremio.Stremio"
    - "Vencord.Vesktop"
    - "Microsoft.VisualStudioCode"
    - "wez.wezterm"
    - "9NKSQGP7F2NH" # WhatsApp Desktop
    - "Zen-Team.Zen-Browser"