# ╭──────────────────────────────────────────────────────────╮
# │ Windows                                                  │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  win:
    winget:
      - "sharkdp.bat"
      - "dandavison.delta"
      - "Microsoft.DotNet.SDK.8"
      - "eza-community.eza"
      - "sharkdp.fd"
      - "Fastfetch-cli.Fastfetch"
      - "junegunn.fzf"
      - "JesseDuffield.lazygit"
      - "jftuga.less"
      - "LLVM.LLVM"
      - "Neovim.Neovim"
      - "Proton.ProtonDrive"
      - "Proton.ProtonMail"
      - "Proton.ProtonVPN"
      - "JanDeDobbeleer.OhMyPosh"
      - "ojdkbuild.ojdkbuild"
      - "BurntSushi.ripgrep.MSVC"
      - "mbuilov.sed"
      - "Microsoft.VCRedist.2015+.x64"
      - "ajeetdsouza.zoxide"
    modules:
      - "PSFzf"
apps:
  win:
    winget:
      - "Bitwarden.Bitwarden"
      - "Google.Chrome"
      - "Docker.DockerDesktop"
      - "Logitech.OptionsPlus"
      - "Nextcloud.NextcloudDesktop"
      - "Microsoft.PowerToys"
      - "Nilesoft.Shell"
      - "OpenWhisperSystems.Signal"
      - "Spotify.Spotify"
      - "Vencord.Vesktop"
      - "Microsoft.VisualStudio.2022.Community"
      - "Microsoft.VisualStudioCode"
      - "wez.wezterm"
      - "9NKSQGP7F2NH" # WhatsApp Desktop
      - "Zen-Team.Zen-Browser"
    manual:
      - "AnkerWork"
      - "Geist Sans"
      - "Geist Mono Nerd Font"
      - "Symbols Nerd Font"
      - "Noto Color Emoji Font"
