# ╭──────────────────────────────────────────────────────────╮
# │ WORK                                                     │
# ╰──────────────────────────────────────────────────────────╯

---
apps:
  work:
    - name: "MySQL"
      win: "Oracle.MySQL"
    - name: "MySQL Workbench"
      win: "Oracle.MySQLWorkbench"
