# ╭──────────────────────────────────────────────────────────╮
# │ WSL                                                      │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  wsl:
    pacman:
      - "openssh"
    paru: []
