# ╭──────────────────────────────────────────────────────────╮
# │ WSL                                                      │
# ╰──────────────────────────────────────────────────────────╯

---
packages:
  wsl:
    pacman: []
    paru: []
